// <auto-generated />
namespace ShopManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_CreatedBy_CreatedDate_ModifiedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_CreatedBy_CreatedDate_ModifiedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202111081238256_Add_CreatedBy_CreatedDate_ModifiedDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
